### ISSUE TITLE
Cannot find files to run exercises

### ISSUE THREAD

**Issue by mklvcm** [stack-of-tasks/tsid#64]
Hi there!

I'm trying to run exercises and looks like some data files are missing/invalid.

First, this is my problem with UR5 file. Even though file is there and looks reasonable, it does not work.

![Shot1](https://user-images.githubusercontent.com/54096564/73114411-46807e80-3f6e-11ea-8bd6-0be23404bdcb.png)

Second, this is my problem with Romeo file.

![Shot2](https://user-images.githubusercontent.com/54096564/73114414-4c765f80-3f6e-11ea-9bdd-63322e3b8222.png)

Any help will be appreciated.

Thanks,
Misha.

**Comment by andreadelprete** [comment]
> First, this is my problem with UR5 file. Even though file is there and looks reasonable, it does not work.
> 
> ![Shot1](https://user-images.githubusercontent.com/54096564/73114411-46807e80-3f6e-11ea-8bd6-0be23404bdcb.png)

Actually it seems it's not finding the urdf file even after you've specified the environment variable. The path seems correct, but you can try copy-pasting it to check if that's really the case. If the path is correct, another potential problem may be the file permissions: maybe the script doesn't have read rights on that file. 
 
> Second, this is my problem with Romeo file.
> 
> ![Shot2](https://user-images.githubusercontent.com/54096564/73114414-4c765f80-3f6e-11ea-9bdd-63322e3b8222.png)

This is because before launching ex_4_walking you should run [ex_4_plan_LIPM_romeo](https://github.com/stack-of-tasks/tsid/blob/master/exercizes/ex_4_plan_LIPM_romeo.py) (which BTW depends on [LMPC walking](https://github.com/ahmadgazar/LMPC_walking)). This will create the npz file that the first script expect.
