### ISSUE TITLE
Force discontinuities when adding contact

### ISSUE THREAD

**Issue by pFernbach** [stack-of-tasks/tsid#88]
Hello,
When adding a new contact, the contact forces of the other contacts computed by the `InverseDynamicsFormulationAccForce` solver are discontinuous. See the plot below that shows the forces along z of the 4 feet of a quadrupedal. At the beginning, only 3 feet are in contact, at t=6.10 the LF foot create contact. 

![contact_normal_force](https://user-images.githubusercontent.com/11633215/81592973-11822580-93bf-11ea-9772-351bb2bb08a0.png)

As you can see, the total force is immediately (in one iteration) distributed between the 4 contacts, which create discontinuities. 

Is there any way in the current implementation to have a 'smooth' change of the force distribution after adding a new contact or do I have to compute a force reference myself and send it with `contact.setForceReference()` ?

**Comment by andreadelprete** [comment]
I think there're two ways to achieve this.

### Adjust the regularization weights
When you [add a new contact](https://github.com/stack-of-tasks/tsid/blob/master/src/formulations/inverse-dynamics-formulation-acc-force.cpp#L230) you can specify the regularization weight. If you initially set this weight quite high (e.g., 1) with a zero reference, I expect the initial force is gonna be almost zero. Then you can smoothly [change this weight](https://github.com/stack-of-tasks/tsid/blob/master/src/formulations/inverse-dynamics-formulation-acc-force.cpp#L265) to reach a small value (e.g., 1e-5), which will allow the contact force to increase.

### Use a time-varying upper bound on normal force
This is already done when you [remove contacts](https://github.com/stack-of-tasks/tsid/blob/master/src/formulations/inverse-dynamics-formulation-acc-force.cpp#L547) so it shouldn't be too hard to do the same when you add contacts, but it's still more work than the previous solution because it requires you to modify the code. The idea is to have a time-varying bound on the normal force, so that it's forced to change smoothly. For the case when you remove a force, what's currently implemented is an upper bound that goes from the current value to almost zero as a linear function of time. The user can decide how fast this transition is using the parameter `transition_duration`.

**Comment by pFernbach** [comment]
This is the result with your first solution:

![contact_normal_force-1](https://user-images.githubusercontent.com/11633215/81797783-84021b00-950f-11ea-979a-7abf1c87e162.png)

It is working as expected, thanks. I had to add `updateRigidContactWeights` to the python API, I will make a PR.

**Comment by andreadelprete** [comment]
Nice!
